version: '3.8'
services:
  backend:
    build: ./iron-server
    ports:
      - "7000:7000"
    volumes:
      - ./iron-server:/app
      - /app/node_modules
    container_name: iron-server
    stdin_open: true
    tty: true 
  frontend:
    build: ./iron-client
    ports:
      - "3000:3000"
    volumes:
      - ./iron-client:/app
      - /app/node_modules
    container_name: iron-client
    stdin_open: true
    tty: true
    depends_on:
      - backend